#Допишите недостающие строки

#Необходимо добавить для работы Java с БД
RUN curl -O https://jdbc.postgresql.org/download/postgresql-42.7.2.jar
CMD ["java", "-cp", ".:postgresql-42.7.2.jar", "App"]
